export enum PermissionType {
    DELIVERY_CREATE = "DELIVERY_CREATE",
    DELIVERY_UPDATE = "DELIVERY_UPDATE",

    DELIVERER_CREATE = "DELIVERER_CREATE",
    DELIVERER_UPDATE = "DELIVERER_UPDATE",

    ADMIN_VIEW = "ADMIN_VIEW",
    ADMIN_CREATE = "ADMIN_CREATE",
    ADMIN_UPDATE = "ADMIN_UPDATE",

    VIEW = "VIEW",
    CREATE = "CREATE",
    UPDATE = "UPDATE"


}