export enum PermissionType {
    DELIVER_CREATE = "DELIVER_CREATE",
    DELIVER_UPDATE = "DELIVER_UPDATE",

    DELIVERER_CREATE = "DELIVERER_CREATE",
    DELIVERER_UPDATE = "DELIVERER_UPDATE",

    ADMIN_VIEW = "ADMIN_VIEW",
    ADMIN_CREATE = "ADMIN_CREATE",
    ADMIN_UPDATE = "ADMIN_UPDATE",

    VIEW = "VIEW",
    CREATE = "CREATE",
    UPDATE = "UPDATE"


}